development:
  adapter: postgresql
  encoding: unicode
  database: hello-rais_development
  pool: 5
  username: hellorails
  password: hellorailspwd

test:
  adapter: postgresql
  encoding: unicode
  database: hello-rais_test
  pool: 5
  username: hellorails
  password: hellorailspwd

production:
  adapter: postgresql
  encoding: unicode
  database: hello-rais_production
  pool: 5
  username: hellorails
  password: hellorailspwd
